/* eslint-disable */
export type Maybe<T> = T | null;
export type InputMaybe<T> = T | null | undefined;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** ISO8601形式の日付(例: 2024-01-15) */
  Date: { input: any; output: any; }
  /** An ISO 8601-encoded date */
  ISO8601Date: { input: any; output: any; }
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: { input: any; output: any; }
  /** ファイルアップロード用のScalar型 */
  Upload: { input: any; output: any; }
};

/** アラート設定の種別 */
export enum AlertSettingKind {
  /** 予算アラート設定 */
  Budget = 'BUDGET',
  /** ペースアラート設定 */
  Pace = 'PACE'
}

/** 全アラート設定 */
export type AlertSettings = Node & {
  __typename?: 'AlertSettings';
  /** 予算アラート設定一覧 */
  budgetAlertSettings: Array<BudgetAlertSetting>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  /** ペースアラート設定一覧 */
  paceAlertSettings: Array<PaceAlertSetting>;
};

/** Autogenerated input type of AttachPhoto */
export type AttachPhotoInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  photo: Scalars['Upload']['input'];
  transactionId: Scalars['ID']['input'];
};

/** Autogenerated return type of AttachPhoto. */
export type AttachPhotoPayload = Node & {
  __typename?: 'AttachPhotoPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  transaction: Transaction;
};

export type Budget = Node & Timestampable & {
  __typename?: 'Budget';
  /** 予算額 */
  amount: Scalars['Int']['output'];
  /** カテゴリ */
  category: Category;
  /** カテゴリID */
  categoryId: Scalars['ID']['output'];
  /** 作成日時 */
  createdAt: Scalars['ISO8601DateTime']['output'];
  /** 予算ID */
  id: Scalars['ID']['output'];
  /** 対象月 */
  month: Scalars['Date']['output'];
  /** 更新日時 */
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type BudgetAlert = Node & Timestampable & {
  __typename?: 'BudgetAlert';
  /** カテゴリ */
  category: Category;
  /** カテゴリID */
  categoryId: Scalars['ID']['output'];
  /** 作成日時 */
  createdAt: Scalars['ISO8601DateTime']['output'];
  /** 予算アラートID */
  id: Scalars['ID']['output'];
  /** アラート閾値（%） */
  threshold: Scalars['Int']['output'];
  /** 更新日時 */
  updatedAt: Scalars['ISO8601DateTime']['output'];
  /** 使用率（%） */
  usagePercent: Scalars['Int']['output'];
};

export type BudgetAlertSetting = Node & Timestampable & {
  __typename?: 'BudgetAlertSetting';
  /** カテゴリ（nil = 全体） */
  category?: Maybe<Category>;
  /** カテゴリID */
  categoryId?: Maybe<Scalars['ID']['output']>;
  /** 作成日時 */
  createdAt: Scalars['ISO8601DateTime']['output'];
  /** 予算アラート設定ID */
  id: Scalars['ID']['output'];
  /** 有効フラグ */
  isActive: Scalars['Boolean']['output'];
  /** 第1閾値（%） */
  threshold: Scalars['Int']['output'];
  /** 第2閾値（%） */
  threshold2?: Maybe<Scalars['Int']['output']>;
  /** 更新日時 */
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type Category = Node & Timestampable & {
  __typename?: 'Category';
  /** カテゴリ種別（FixedCategory / VariableCategory） */
  categoryType: Scalars['String']['output'];
  /** 子カテゴリ一覧 */
  children: Array<Category>;
  /** 表示色 */
  color?: Maybe<Scalars['String']['output']>;
  /** 作成日時 */
  createdAt: Scalars['ISO8601DateTime']['output'];
  /** カテゴリID */
  id: Scalars['ID']['output'];
  /** カテゴリ名 */
  name: Scalars['String']['output'];
  /** 親カテゴリ */
  parent?: Maybe<Category>;
  /** 親カテゴリID */
  parentId?: Maybe<Scalars['ID']['output']>;
  /** 表示順 */
  sortOrder: Scalars['Int']['output'];
  /** 紐づく取引件数 */
  transactionsCount: Scalars['Int']['output'];
  /** 更新日時 */
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** カテゴリ別支出内訳 */
export type CategoryBreakdown = Node & {
  __typename?: 'CategoryBreakdown';
  /** 合計金額（円） */
  amount: Scalars['Int']['output'];
  /** 予算額（円） */
  budgetAmount?: Maybe<Scalars['Int']['output']>;
  /** カテゴリID */
  categoryId: Scalars['ID']['output'];
  /** カテゴリ名 */
  categoryName: Scalars['String']['output'];
  /** 1日あたり使用可能額（円） */
  dailyAmount?: Maybe<Scalars['Int']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  /** ペース状況（GREEN/YELLOW/RED）。当月のみ返す */
  paceStatus?: Maybe<PaceStatus>;
  /** 全体に占める割合（%） */
  percentage: Scalars['Float']['output'];
  /** 残り予算（円） */
  remainingAmount?: Maybe<Scalars['Int']['output']>;
};

/** Autogenerated input type of CreateCategory */
export type CreateCategoryInput = {
  /** FixedCategory または VariableCategory */
  categoryType: Scalars['String']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
  name: Scalars['String']['input'];
};

/** Autogenerated return type of CreateCategory. */
export type CreateCategoryPayload = Node & {
  __typename?: 'CreateCategoryPayload';
  category?: Maybe<Category>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
};

/** Autogenerated input type of CreateTransaction */
export type CreateTransactionInput = {
  amount: Scalars['Int']['input'];
  categoryId?: InputMaybe<Scalars['ID']['input']>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  purchasedAt: Scalars['ISO8601Date']['input'];
  source: TransactionSource;
  storeName: Scalars['String']['input'];
};

/** Autogenerated return type of CreateTransaction. */
export type CreateTransactionPayload = Node & {
  __typename?: 'CreateTransactionPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  transaction?: Maybe<Transaction>;
};

/** Autogenerated input type of DeleteBudget */
export type DeleteBudgetInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of DeleteBudget. */
export type DeleteBudgetPayload = Node & {
  __typename?: 'DeleteBudgetPayload';
  budget?: Maybe<Budget>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
};

/** Autogenerated input type of DeleteCategory */
export type DeleteCategoryInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of DeleteCategory. */
export type DeleteCategoryPayload = Node & {
  __typename?: 'DeleteCategoryPayload';
  category?: Maybe<Category>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
};

/** Autogenerated input type of DeleteTransaction */
export type DeleteTransactionInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of DeleteTransaction. */
export type DeleteTransactionPayload = Node & {
  __typename?: 'DeleteTransactionPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  success: Scalars['Boolean']['output'];
};

/** Autogenerated input type of MarkAllNotificationsAsRead */
export type MarkAllNotificationsAsReadInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of MarkAllNotificationsAsRead. */
export type MarkAllNotificationsAsReadPayload = Node & {
  __typename?: 'MarkAllNotificationsAsReadPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  count: Scalars['Int']['output'];
  errors: Array<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
};

/** Autogenerated input type of MarkNotificationAsRead */
export type MarkNotificationAsReadInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of MarkNotificationAsRead. */
export type MarkNotificationAsReadPayload = Node & {
  __typename?: 'MarkNotificationAsReadPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  notification?: Maybe<Notification>;
};

/** 月次支出集計 */
export type MonthlySummary = Node & {
  __typename?: 'MonthlySummary';
  /** 合計予算額（円） */
  budgetAmount: Scalars['Int']['output'];
  /** カテゴリ別内訳 */
  categoryBreakdowns: Array<CategoryBreakdown>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  /** 残額（円） */
  remainingAmount: Scalars['Int']['output'];
  /** 合計支出額（円） */
  totalAmount: Scalars['Int']['output'];
};

export type Mutation = Node & {
  __typename?: 'Mutation';
  /** Transactionに写真を添付する */
  attachPhoto?: Maybe<AttachPhotoPayload>;
  /** Categoryを作成する */
  createCategory?: Maybe<CreateCategoryPayload>;
  /** Transactionを作成する */
  createTransaction?: Maybe<CreateTransactionPayload>;
  /** Budgetを削除する */
  deleteBudget?: Maybe<DeleteBudgetPayload>;
  /** Categoryを削除する */
  deleteCategory?: Maybe<DeleteCategoryPayload>;
  /** Transactionを削除する */
  deleteTransaction?: Maybe<DeleteTransactionPayload>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  /** 全未読通知を既読にする */
  markAllNotificationsAsRead?: Maybe<MarkAllNotificationsAsReadPayload>;
  /** 通知を既読にする */
  markNotificationAsRead?: Maybe<MarkNotificationAsReadPayload>;
  /** Categoryを更新する */
  updateCategory?: Maybe<UpdateCategoryPayload>;
  /** 店名とカテゴリのマッピングを作成または更新する */
  updateStoreMapping?: Maybe<UpdateStoreMappingPayload>;
  /** Transactionを更新する */
  updateTransaction?: Maybe<UpdateTransactionPayload>;
  /** アラート設定を作成または更新する（予算・ペース両対応） */
  upsertAlertSetting?: Maybe<UpsertAlertSettingPayload>;
  /** Budgetを作成または更新する */
  upsertBudget?: Maybe<UpsertBudgetPayload>;
};


export type MutationAttachPhotoArgs = {
  input: AttachPhotoInput;
};


export type MutationCreateCategoryArgs = {
  input: CreateCategoryInput;
};


export type MutationCreateTransactionArgs = {
  input: CreateTransactionInput;
};


export type MutationDeleteBudgetArgs = {
  input: DeleteBudgetInput;
};


export type MutationDeleteCategoryArgs = {
  input: DeleteCategoryInput;
};


export type MutationDeleteTransactionArgs = {
  input: DeleteTransactionInput;
};


export type MutationMarkAllNotificationsAsReadArgs = {
  input: MarkAllNotificationsAsReadInput;
};


export type MutationMarkNotificationAsReadArgs = {
  input: MarkNotificationAsReadInput;
};


export type MutationUpdateCategoryArgs = {
  input: UpdateCategoryInput;
};


export type MutationUpdateStoreMappingArgs = {
  input: UpdateStoreMappingInput;
};


export type MutationUpdateTransactionArgs = {
  input: UpdateTransactionInput;
};


export type MutationUpsertAlertSettingArgs = {
  input: UpsertAlertSettingInput;
};


export type MutationUpsertBudgetArgs = {
  input: UpsertBudgetInput;
};

/** An object with an ID. */
export type Node = {
  /** ID of the object. */
  id: Scalars['ID']['output'];
};

/** 通知の対象（BudgetAlert、PaceAlert、またはUnclassifiedAlert） */
export type Notifiable = BudgetAlert | PaceAlert | UnclassifiedAlert;

export type Notification = Node & Timestampable & {
  __typename?: 'Notification';
  /** 作成日時 */
  createdAt: Scalars['ISO8601DateTime']['output'];
  /** 通知ID */
  id: Scalars['ID']['output'];
  /** 通知の対象（BudgetAlertまたはUnclassifiedAlert） */
  notifiable: Notifiable;
  /** 既読日時 */
  readAt?: Maybe<Scalars['ISO8601DateTime']['output']>;
  /** 更新日時 */
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** The connection type for Notification. */
export type NotificationConnection = {
  __typename?: 'NotificationConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<NotificationEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<Notification>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type NotificationEdge = {
  __typename?: 'NotificationEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<Notification>;
};

export type PaceAlert = Node & Timestampable & {
  __typename?: 'PaceAlert';
  /** カテゴリ */
  category: Category;
  /** カテゴリID */
  categoryId: Scalars['ID']['output'];
  /** 作成日時 */
  createdAt: Scalars['ISO8601DateTime']['output'];
  /** ペースアラートID */
  id: Scalars['ID']['output'];
  /** 対象月 */
  month: Scalars['ISO8601Date']['output'];
  /** 回復日時 */
  recoveredAt?: Maybe<Scalars['ISO8601DateTime']['output']>;
  /** 発火日時 */
  triggeredAt: Scalars['ISO8601DateTime']['output'];
  /** 更新日時 */
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type PaceAlertSetting = Node & Timestampable & {
  __typename?: 'PaceAlertSetting';
  /** 送信開始日（例: 5 = 5日以降） */
  activeFromDay: Scalars['Int']['output'];
  /** カテゴリ */
  category: Category;
  /** カテゴリID */
  categoryId: Scalars['ID']['output'];
  /** 作成日時 */
  createdAt: Scalars['ISO8601DateTime']['output'];
  /** ペースアラート設定ID */
  id: Scalars['ID']['output'];
  /** 有効フラグ */
  isActive: Scalars['Boolean']['output'];
  /** 閾値（%、100超） */
  threshold: Scalars['Int']['output'];
  /** 更新日時 */
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** 予算消化ペースの状態 */
export enum PaceStatus {
  /** 余裕あり */
  Green = 'GREEN',
  /** 危険・超過 */
  Red = 'RED',
  /** 要注意 */
  Yellow = 'YELLOW'
}

/** Information about pagination in a connection. */
export type PageInfo = {
  __typename?: 'PageInfo';
  /** When paginating forwards, the cursor to continue. */
  endCursor?: Maybe<Scalars['String']['output']>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars['Boolean']['output'];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars['Boolean']['output'];
  /** When paginating backwards, the cursor to continue. */
  startCursor?: Maybe<Scalars['String']['output']>;
};

export type Query = Node & {
  __typename?: 'Query';
  /** 全アラート設定 */
  alertSettings: AlertSettings;
  /** 予算一覧（月フィルタ可） */
  budgets: Array<Budget>;
  /** 全カテゴリ一覧 */
  categories: Array<Category>;
  /** ID指定でカテゴリを1件取得 */
  category?: Maybe<Category>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  /** 月次支出集計 */
  monthlySummary: MonthlySummary;
  /** Fetches an object given its ID. */
  node?: Maybe<Node>;
  /** Fetches a list of objects given a list of IDs. */
  nodes?: Maybe<Array<Maybe<Node>>>;
  /** 通知一覧 */
  notifications: NotificationConnection;
  /** ID指定で取引を1件取得 */
  transaction?: Maybe<Transaction>;
  /** 取引一覧（フィルタ可） */
  transactions: TransactionConnection;
};


export type QueryBudgetsArgs = {
  month?: InputMaybe<Scalars['Date']['input']>;
};


export type QueryCategoryArgs = {
  id: Scalars['ID']['input'];
};


export type QueryMonthlySummaryArgs = {
  month: Scalars['Int']['input'];
  year: Scalars['Int']['input'];
};


export type QueryNodeArgs = {
  id: Scalars['ID']['input'];
};


export type QueryNodesArgs = {
  ids: Array<Scalars['ID']['input']>;
};


export type QueryNotificationsArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  unreadOnly?: InputMaybe<Scalars['Boolean']['input']>;
};


export type QueryTransactionArgs = {
  id: Scalars['ID']['input'];
};


export type QueryTransactionsArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  categoryId?: InputMaybe<Scalars['ID']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  month?: InputMaybe<Scalars['Int']['input']>;
  year?: InputMaybe<Scalars['Int']['input']>;
};

export type StoreCategoryMapping = Node & Timestampable & {
  __typename?: 'StoreCategoryMapping';
  /** カテゴリ */
  category: Category;
  /** カテゴリID */
  categoryId: Scalars['ID']['output'];
  /** 作成日時 */
  createdAt: Scalars['ISO8601DateTime']['output'];
  /** マッピングID */
  id: Scalars['ID']['output'];
  /** 店舗名 */
  storeName: Scalars['String']['output'];
  /** 更新日時 */
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type Subscription = {
  __typename?: 'Subscription';
  /** 通知が作成されたときに発火する */
  notificationCreated: Notification;
};

export type Timestampable = {
  /** 作成日時 */
  createdAt: Scalars['ISO8601DateTime']['output'];
  /** 更新日時 */
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type Transaction = Node & Timestampable & {
  __typename?: 'Transaction';
  /** 金額 */
  amount: Scalars['Int']['output'];
  /** カテゴリ */
  category?: Maybe<Category>;
  /** カテゴリID */
  categoryId?: Maybe<Scalars['ID']['output']>;
  /** 作成日時 */
  createdAt: Scalars['ISO8601DateTime']['output'];
  /** 取引ID */
  id: Scalars['ID']['output'];
  /** メモ */
  memo?: Maybe<Scalars['String']['output']>;
  /** 写真URL */
  photoUrl?: Maybe<Scalars['String']['output']>;
  /** 購入日 */
  purchasedAt: Scalars['Date']['output'];
  /** 入力元 */
  source: TransactionSource;
  /** 店舗名 */
  storeName: Scalars['String']['output'];
  /** 更新日時 */
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** The connection type for Transaction. */
export type TransactionConnection = {
  __typename?: 'TransactionConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<TransactionEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<Transaction>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** 総件数 */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type TransactionEdge = {
  __typename?: 'TransactionEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<Transaction>;
};

/** 取引の入力元 */
export enum TransactionSource {
  /** 手動入力 */
  Manual = 'MANUAL',
  /** iPhoneショートカット経由 */
  Shortcut = 'SHORTCUT'
}

export type UnclassifiedAlert = Node & Timestampable & {
  __typename?: 'UnclassifiedAlert';
  /** 未分類取引件数 */
  count: Scalars['Int']['output'];
  /** 作成日時 */
  createdAt: Scalars['ISO8601DateTime']['output'];
  /** 未分類アラートID */
  id: Scalars['ID']['output'];
  /** 更新日時 */
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** Autogenerated input type of UpdateCategory */
export type UpdateCategoryInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
  name?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of UpdateCategory. */
export type UpdateCategoryPayload = Node & {
  __typename?: 'UpdateCategoryPayload';
  category?: Maybe<Category>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
};

/** Autogenerated input type of UpdateStoreMapping */
export type UpdateStoreMappingInput = {
  categoryId: Scalars['ID']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  storeName: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateStoreMapping. */
export type UpdateStoreMappingPayload = Node & {
  __typename?: 'UpdateStoreMappingPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  storeMapping?: Maybe<StoreCategoryMapping>;
};

/** Autogenerated input type of UpdateTransaction */
export type UpdateTransactionInput = {
  amount?: InputMaybe<Scalars['Int']['input']>;
  categoryId?: InputMaybe<Scalars['ID']['input']>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
  purchasedAt?: InputMaybe<Scalars['ISO8601Date']['input']>;
  source?: InputMaybe<TransactionSource>;
  storeName?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of UpdateTransaction. */
export type UpdateTransactionPayload = Node & {
  __typename?: 'UpdateTransactionPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  transaction?: Maybe<Transaction>;
};

/** Autogenerated input type of UpsertAlertSetting */
export type UpsertAlertSettingInput = {
  /** 送信開始日 ペースアラートのみ */
  activeFromDay?: InputMaybe<Scalars['Int']['input']>;
  /** カテゴリID（nilで全体） */
  categoryId?: InputMaybe<Scalars['ID']['input']>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  /** 有効フラグ */
  isActive?: InputMaybe<Scalars['Boolean']['input']>;
  /** 設定種別（BUDGET / PACE） */
  settingType: AlertSettingKind;
  /** 閾値（%） */
  threshold: Scalars['Int']['input'];
  /** 第2閾値（%）予算アラートのみ */
  threshold2?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of UpsertAlertSetting. */
export type UpsertAlertSettingPayload = Node & {
  __typename?: 'UpsertAlertSettingPayload';
  budgetAlertSetting?: Maybe<BudgetAlertSetting>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  paceAlertSetting?: Maybe<PaceAlertSetting>;
};

/** Autogenerated input type of UpsertBudget */
export type UpsertBudgetInput = {
  amount: Scalars['Int']['input'];
  categoryId: Scalars['ID']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  month: Scalars['Date']['input'];
};

/** Autogenerated return type of UpsertBudget. */
export type UpsertBudgetPayload = Node & {
  __typename?: 'UpsertBudgetPayload';
  budget?: Maybe<Budget>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
};
