services:
  db:
    image: postgres:18.3
    environment:
      POSTGRES_USER: kakeibo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_development
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql
